# Generated by Django 3.2 on 2021-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cont', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
